### PR TITLE
Added the ability to send both plain text and html in a message

### PR DESCRIPTION
**Pull request by DmitriySolodkiy**

### CODE REVIEW

**Comment by maestro-1** [comment]
You should make indications/notes that it expects a `message.html` expects a python dictionary.
Your improvements are really nice but don't you think they would be better improved if they added the functionality of sending alternatives alongside plain mail rather than just rehashing sending HTML files alone? 

Here is an inspiring piece of code I found last year which was really helpful for me if you decide consider what I said earlier
https://stackoverflow.com/questions/882712/sending-html-email-using-python

**Comment by sabuhish** [comment]
@DmitriySolodkiy  Thank you for your work. I have reviewed your changes and addition to the module.  There some concerns I would like to discuss. First of all, the module itself has supported both plain and html. subtype in the Config class can be passed to either HTML or plain defaults it is plain. Body in the Config class is also accepting HTML, plain regarding the subtype. No extra argument required for HTML.

**Comment by DmitriySolodkiy** [comment]
> @DmitriySolodkiy Thank you for your work. I have reviewed your changes and addition to the module. There some concerns I would like to discuss. First of all, the module itself has supported both plain and html. subtype in the Config class can be passed to either HTML or plain defaults it is plain. Body in the Config class is also accepting HTML, plain regarding the subtype. No extra argument required for HTML.

Hello @sabuhish! It makes sense to specify both plain text and html, since without plain text messages can sometimes end up in spam. I also implemented the ability to specify both parts taking care of backward compatibility, so that those who already use the package do not have problems when updating to the latest version. I also added the ability to indicate MIME. And in the last commit, I fixed the format of the sender with the name.

**Comment by sabuhish** [comment]
Hello @DmitriySolodkiy Cool! Thank you for your explanation. It sounds like an important point, thank you for taking the time and working on it. I have reviewed it, works like a charm! :+1:  I will merge and release a new version soon. I will ask you to add some information about MultipartSubtypeEnum class and some sort of cases you think it is important to mention for MIME standards. Thanks in advance!

**Comment by sabuhish** [comment]
@DmitriySolodkiy  Hello, we are waiting for your help. If you have some basic understanding of MIME standards you think it will be useful to add, could you please share with us. Thanks.

**Comment by DmitriySolodkiy** [comment]
> @DmitriySolodkiy Hello, we are waiting for your help. If you have some basic understanding of MIME standards you think it will be useful to add, could you please share with us. Thanks.

Hello @sabuhish! Thank you so much for merging my changes. Class MultipartSubtypeEnum contains all possible multipart subtypes that are described in [this article](https://en.wikipedia.org/wiki/MIME#Multipart_subtypes) with links to the corresponding RFC. I think it's also worth noting in the documentation that `multipart/mixed` is the default subtype.

**Comment by sabuhish** [comment]
Thank you @DmitriySolodkiy for your answer. I will just add this link, as detailed information regarding `multipart/mixed`. I got some questions about this, people might be confused. Thanks, again!

**Pull request merged**
