### PR TITLE
intuitive email mocking with fastapi-mail

### PR DESCRIPTION
**Pull request by maestro-1**
A way to allow unit testing of application's email routes with[ pytest ](https://docs.pytest.org/en/latest/)or [unittest](https://docs.python.org/3/library/unittest.html) via mocking by fastapi_mail without actually sending out any emails. 

application.py
```python
conf = ConnectionConfig(
    MAIL_USERNAME = "YourUsername",
    MAIL_PASSWORD = "strong_password",
    MAIL_FROM = "your@email.com",
    MAIL_PORT = 587,
    MAIL_SERVER = "your mail server",
    MAIL_TLS = True,
    MAIL_SSL = False,
    TEMPLATE_FOLDER='./email templates folder',
    # if no indicated SUPPRESS_SEND defaults to 0 (false) as below
    SUPPRESS_SEND=0
)

fm = FastMail(conf)

@app.post("/email")
async def simple_send(email: EmailSchema) -> JSONResponse:
    message = MessageSchema(
        subject="Testing",
        recipients=email.dict().get("email"),  # List of recipients, as many as you can pass 
        body=html,
        subtype="html"
        )
    await fm.send_message(message)
    return JSONResponse(status_code=200, content={"message": "email has been sent"})
```

test.py
```python
from application.py import fm

# make this setting available as a fixture through conftest.py if you plan on using pytest
fm.config.SUPPRESS_SEND = 1

with fm.record_messages() as outbox:
    response = app.test_client.get("/email")
    assert len(outbox) == 1
    assert outbox[0].subject == "Testing"
```

This will allow for more intuitive application mail testing via mocking and avoids bugging out email servers with dummy emails resulting in a potential block from that server, and this also eliminates the complexity of having to create a personal server to test sending outgoing mails.

This PR was heavily influenced by the Flask-Mail testing function

### CODE REVIEW

**Comment by sabuhish** [comment]
@maestro-1  Sorry for keeping your PR. I was just busy with other projects. I have reviewed it, this an awesome feature for the module. :100:  :+1:  I appreciate your given time and making it possible. Thank you! Your efforts are highly appreciated!

**Comment by maestro-1** [comment]
@sabuhish   It's all good. I do have a few more PRs to raise. The primary aim of my next PR will be to fix #20.
I have looked at your at some of your other projects and they look fantastic, hopefully, I will get the time to contribute to those as well in any way I can. Great job on these libraries

**Comment by sabuhish** [comment]
@maestro-1  Thank you for following the module, you have been doing a lot of great works so far. We did some research about this (#20), skipped for later. We can share and discuss. Thank you for your nice words they mean a lot really.  We highly emphasized on (fastapi-mqtt)[https://github.com/sabuhish/fastapi-mqtt]  last week that is where we skipped #20. It took a long time to make the decision and design the architecture of it and finally it is ready to use. I tried to document every single point. Had a discussion on fastapi as well, you can follow the disscuin here I made (issue 1422)[https://github.com/tiangolo/fastapi/issues/1422]. With @Turall  and @AliyevH we have some other open-source projects as well which still be working in private repos sooner we will release them. We will do as much as we can. Your efforts, and contributions make these libraries awesome, thank you again!

**Comment by sabuhish** [comment]
@maestro-1 Thank you for following the module, you have been doing a lot of great works so far. We did some research about this (#20), skipped for later. We can share and discuss. Thank you for your nice words they mean a lot really. We highly emphasized on fastapi-mqtt last week that is where we skipped #20. It took a long time to make the decision and design the architecture of it and finally it is ready to use. I tried to document every single point. With @Turall and @AliyevH we have some other open-source projects as well which still be working in private repos sooner we will release them. We will do as much as we can. Your efforts, and contributions make these libraries awesome, thank you again!

**Comment by maestro-1** [comment]
@sabuhish I would love very much to share and discuss on #20 when we get the time. I will also look in fastapi-mqtt if you like to see if there is any way I can assist. And if you need extra hands in some of the private repos, I wouldn't mind that either to help speed things up because it has been an absolute delight in helping out so far

**Comment by sabuhish** [comment]
Thank you for your help, you are an awesome contributor! I will let you know about this, we will get in touch I hope soon. We would love to see you in our one of the private repos :+1:  We all happy to see your work, thanks for taking the time and analyzing  we much appreciated it :)

**Comment by sabuhish** [comment]
Hey @maestro-1! How is going? Remember I told you one project we were hardly working on, we have made minimal work with requirements and currently operates as expected. With team members, we wanted to ask if are interested to join and see code base and participate :) If you are in I would ask you to paste your email, or just send me a mail so I can get your mail address for an invitation.  
 
 sabuhi.shukurov@gmail.com

**Pull request merged**
