### PR TITLE
Use credentials configuration option.

### PR DESCRIPTION
**Pull request by pboers1988**
Created this PR because we have a use case where we do not need to pass credentials to the mail server. Created a toggle in the configuration to login during session creation or not. Our mail server does not use SMTP AUTH, in fact the module is not even loaded, and therefore we get an exception when connecting.

I also fixed up a circular dependancy with the version file that occurred during a clean install. Because it was parsing the __init__ in fastapi_mail it was importing dependancies that had not been installed yet. This happens in a clean venv.

### CODE REVIEW

**Comment by pboers1988** [comment]
Is a solution for #35

**Comment by sabuhish** [comment]
a while we were talking with @Turall whatever authentication can be without username and password. :) Later checked my phone so you PR. What a coincidence! Thank you! We thought if it is only possible if locally running SMTP server, your case confirms it can be applied to other servers. I will try to realase today. 
I think this closes #35

Before that  I will ask you to describe it in README.md so others can also work around. Thanks for great work! Cheers 🎉

**Comment by jaimebustose** [comment]
Guys I have a bug on 0.3.3.0:

`python: ModuleNotFoundError: No module named 'version'`

**Comment by sabuhish** [comment]
can you check with version 0.3.3.1 should be fixed. Let me know.

**Pull request merged**
