### PR TITLE
remove confusing print()

### PR DESCRIPTION
**Pull request by tsasao**

### CODE REVIEW

**Comment by so-rose** [comment]
+1 for this, I was running a local script to send mails out recently, and it complained about lacking httpx and aioredis - even though I needed neither (or did I?)

Overall distracting until I perused the source code.

**Comment by sabuhish** [comment]
Thanks for the MR, I forgot to remove it while testing!

**Comment by Feijo** [comment]
Hi @sabuhish when is this going to be released?

**Comment by sabuhish** [comment]
I will release it today

**Pull request merged**
