### PR TITLE
chore: update dependencies for support pydantic V2 and adapt code in consequences

### LINKED ISSUE #194: Support pydantic v2
Hello,
I use fastapi and fastapi-mail and try to upgrade fastapi version 0.100.0b2 to prepare pydantic v2.
But it is impossible to upgrade fastapi package due to dependency conflict like below:
```
The conflict is caused by:
    The user requested pydantic==2.0
    fastapi 0.100.0b2 depends on pydantic!=1.8, !=1.8.1, <3.0.0 and >=1.7.4
    fastapi-mail 1.3.1 depends on pydantic<2.0 and >=1.8
```
Could you make new beta release for this?
Best Regards,

### PR DESCRIPTION
**Pull request by fchancel**
Update pydantic to v2, fastapi to v0.100, email-validator to v2.0 packages.
Updated code according to pydantic V1 to V2 migration documentation. 
Fix #194

### CODE REVIEW

**Comment by chrisK824** [comment]
@sabuhish this incompatibility is blocking updates into pydantic v2 which came out already with tons of enhancements.

Do you plan to merge this request and update dependencies or should we move out to some other solution?

**Comment by ahvincent** [comment]
@sabuhish Need any help with this update? Currently blocking my team's update to Pedantic v2 as well. Let me know if I can help out anywhere.

**Comment by sabuhish** [comment]
Thank you, guys, for the report and work on it, changes LGTM. I would ask @fchancel to fix the linter please, it suppose to run on the pull request, but I realized it is manual work. Once it is fixed I will merge and realease it. Good work!

**Comment by fchancel** [comment]
@sabuhish I fixed the linter. Only mypy errors persist. 32 already existing errors and an additional one due to the fact that mypy is not updated and therefore the expected formats for Pydantic do not correspond.
I'm working on a new PR to remove all mypy errors and alerts.

**Comment by sabuhish** [comment]
Thank you for your work, sorry for being late and busy. I believe so also, many people are waiting for this PR to be merged, it is worth having it in the next release. I will have a look at your next PR too. Thanks again for your efforts, in helping the growth of this library!

**Pull request merged**
