### PR TITLE
115 multipart html and plain text emails

### PR DESCRIPTION
**Pull request by Synrom**
This pull request solves #115 by adding an alternative body to the `MessageSchema` and implementing functionalities for adding the alternative body in the `MailMsg` class.

### CODE REVIEW

**Comment by sabuhish** [comment]
Hi @Synrom, thanks for your PR.
Why do we make the library more complex by adding attributes like `alternative_body`?
Seems to me alternative_body attribute is a copy of the body, we already have a feature specifying the message should be plain or HTML.

Could you please clarify more in detail the purpose of this PR? The only difference I see only flipping the plain with the HTML value.

**Comment by Synrom** [comment]
Hi @sabuhish , 
the purpose of `alternative_body` is to have both a plain and a HTML attachment. 
This is so you don't have to write HTML only emails, but can send both formats at the same time. 
The receiving client can then choose what to display.

**Comment by sabuhish** [comment]
aren't we having this already implemented in the body attribute and with HTML and plain options?

**Comment by Synrom** [comment]
It could very well be, that Ive miss-read or overlooked something in the code, but I thought the feature to have an alternative body wasn't there yet.
How would you create an email with an alternative body in the current version?

**Comment by Synrom** [comment]
Here is an exemplary implementation of what I mean using the `email` package: [Sending html or text email with or without attachment](https://code.activestate.com/recipes/576858-send-html-or-text-email-with-or-without-attachment/).
To my understanding this is not yet implemented in fastapi-mail.

**Comment by sr-verde** [comment]
I would like to politely ask @sabuhish again to merge this PR as it is really useful. Having both plain text and HTML in a single email is a base feature in almost all mail libs.

**Comment by sabuhish** [comment]
Thanks to each of you guys for your contribution and for helping the growth of this library. I appreciate your work and patience here. I apologize for being late, I was too busy with side projects and could not manage my time correctly, my aim was to read and understand what is happening, therefore it took a bit of time. The changes look great to me, very well done. The only thing I may ask is to provide more examples in the documentation, you know without documentation it is a bit difficult to implement for others, if we want to make it easy for others we should provide direction to them. Thanks for the hard work and nice feature again, I will go and merge these changes and will release the new version.

**Pull request merged**
