### PR TITLE
Feature adding reply to support

### PR DESCRIPTION
**Pull request by jdvalentine**
Please let me know what changes you'd like. I went back to RFC 2822 to check what I've done is correct, and I've tested with this version as a local package in my own project. It seems to work correctly but I would appreciate your advice.

I have run the tests but did not create the SMTP endpoint. I'm confident of my changes, though.

### CODE REVIEW

**Comment by sabuhish** [comment]
@jdvalentine  thank you for the workaround, you did great work! Could you please add an example to docs as well others can also benefit from it. 

Thanks again!

**Comment by jdvalentine** [comment]
> Could you please add an example to docs as well with an explanation so others can also benefit from it.

Good point. I've updated the example. Usage is very similar to BCC. Thanks for considering this!

**Comment by sabuhish** [comment]
Thanks again for updating! I am not sure maybe I am doing something wrong, but I tested with two different mail server not able to achieve this functionality. It still unclear for me, unfortunately. Maybe I am doing something wrong, I read RFC 2822, your PR is everything fine but cant figure out why not getting reply-to yet.

**Comment by jdvalentine** [comment]
> I read RFC 2822, your PR is everything fine but cant figure out why not getting reply-to yet.

It's more the client that must support it. The Gmail Web client doesn't, for example. I use Thunderbird which uses it.

Can you check the raw message you receive and confirm it has the Reply-To header? It works for me in testing.

**Comment by sabuhish** [comment]
> > I read RFC 2822, your PR is everything fine but cant figure out why not getting reply-to yet.
> 
> It's more the client that must support it. The Gmail Web client doesn't, for example. I use Thunderbird which uses it.
> 
> Can you check the raw message you receive and confirm it has the Reply-To header? It works for me in testing.

Oh yes I see that now. One of the server was gmail actually.  Yes it does has this.

**Comment by jdvalentine** [comment]
> > > I read RFC 2822, your PR is everything fine but cant figure out why not getting reply-to yet.
> > 
> > 
> > It's more the client that must support it. The Gmail Web client doesn't, for example. I use Thunderbird which uses it.
> > Can you check the raw message you receive and confirm it has the Reply-To header? It works for me in testing.
> 
> Oh yes I see that now. One of the server was gmail actually. Yes it does has this. 

Looks good!

**Comment by sabuhish** [comment]
> 
> 
> 
> 
> > > > I read RFC 2822, your PR is everything fine but cant figure out why not getting reply-to yet.
> > > 
> > > 
> > > It's more the client that must support it. The Gmail Web client doesn't, for example. I use Thunderbird which uses it.
> > > Can you check the raw message you receive and confirm it has the Reply-To header? It works for me in testing.
> > 
> > Oh yes I see that now. One of the server was gmail actually. Yes it does has this. 
> 
> Looks good!

Then we are good to go!

**Comment by sabuhish** [comment]
I do appreciate your given time, thanks for working around!

**Pull request merged**
