### PR TITLE
Adds custom headers and mime  type to attachments (#92)

### LINKED ISSUE #92: Allow creating custom headers for attachments
Use case - attaching html images with Content-ID header to reference them in HTML content of email based on [RFC2392](https://datatracker.ietf.org/doc/html/rfc2392)

How to do it:
- Modify MessageSchema to allow setting custom headers, like this
```python

message = MessageSchema(
        subject=subject,
        recipients=recipients,
        html=html,
        subtype="html",
        attachments=[{"file": "/path/to/file", "headers":{"Content-ID": "<image1>"}, "mime_type" : "image", "mime_subtype": "png"}]
    )
```
`file` parameter can be as now, UploadFile and path

As it's hard to automagically import mime class  as they dont' have the same API, it's possible to do it through MIMEBase

So it's possible to add custom headers and override `mime_type` used in `MIMEBase` with `type` and `subtype` attributes

and in `MailMsg`, in `attach_file` method, unpack the structure and add headers.

I can code it if this is fine @sabuhish

### PR DESCRIPTION
**Pull request by wjurkowlaniec**
Fixes #92

### CODE REVIEW

**Review by marktennyson — APPROVED** [review]

**Review by marktennyson — COMMENTED** [review]
at-least remove the `print` statement.

**Comment by wjurkowlaniec** [comment]
@marktennyson done

**Comment by sabuhish** [comment]
@wjurkowlaniec Thank you for your work! I have also added tests for custom headers and refactored a bit of codebase. Now we can merge to the master.

**Review by sabuhish — APPROVED** [review]

**Comment by wjurkowlaniec** [comment]
thank you :)

**Pull request merged**
