### PR TITLE
remove TEMPLATE_FOLDER validation because Pydantic DirectoryPath already does that…

### PR DESCRIPTION
**Pull request by andredias**
`fastapi-mail` `ConnectionConfig` does not need to check for a valid `TEMPLATE_FOLDER` value since `pydantic`'s `DirectoryPath` already does that: https://pydantic-docs.helpmanual.io/usage/types/#pydantic-types

### CODE REVIEW

**Comment by andredias** [comment]
It closes #86

**Comment by Turall** [comment]
Hi @andredias, thank you for your PR. Can you add a  traversal check function? This function check for path traversal security vulnerability.

**Comment by andredias** [comment]
Do you mean https://owasp.org/www-community/attacks/Path_Traversal? I don't believe it applies to this case because it is not a parameter received from an external and unreliable source. Instead, it is a configuration one defined by developers.

**Comment by Turall** [comment]
> Do you mean https://owasp.org/www-community/attacks/Path_Traversal? I don't believe it applies to this case because it is not a parameter received from an external and unreliable source. Instead, it is a configuration one defined by developers.

I think you are right. Great job. Please fix the tests and I will merge this PR. 👍

**Comment by markkkkas** [comment]
guys pls merge it....

**Comment by maestro-1** [comment]
Very good PR. Great job

**Comment by andredias** [comment]
> > Do you mean https://owasp.org/www-community/attacks/Path_Traversal? I don't believe it applies to this case because it is not a parameter received from an external and unreliable source. Instead, it is a configuration one defined by developers.
> 
> I think you are right. Great job. Please fix the tests and I will merge this PR. +1

Which test is failing?

**Comment by andredias** [comment]
By the way, is there interest in migrating the dependency management to `poetry`? It would make it easier to test and contribute to the project. I can provide another PR for that if there is.

**Comment by Turall** [comment]
> > > Do you mean https://owasp.org/www-community/attacks/Path_Traversal? I don't believe it applies to this case because it is not a parameter received from an external and unreliable source. Instead, it is a configuration one defined by developers.
> > 
> > 
> > I think you are right. Great job. Please fix the tests and I will merge this PR. +1
> 
> Which test is failing?
```
tests/test_connection.py::test_jinja_message 
tests/test_redis_config.py::test_redis_checker

These test cases failed.

**Comment by Turall** [comment]
> By the way, is there interest in migrating the dependency management to `poetry`? It would make it easier to test and contribute to the project. I can provide another PR for that if there is.

Great idea, it will be very useful.

**Comment by andredias** [comment]
The issue with test `tests/test_connection.py::test_jinja_message` is not related to this PR. Neither the other one, to be honest. But I was able to update the dependency from `aioredis` to version `2.0.0` and fix the latter.

**Comment by Turall** [comment]
> The issue with test `tests/test_connection.py::test_jinja_message` is not related to this PR. Neither the other one, to be honest. But I was able to update the dependency from `aioredis` to version `2.0.0` and fix the latter.

@andredias great job, thank you for your PR, I will merge this PR.

**Comment by markkkkas** [comment]
can you release it aswell? Cant use this with poetry when pointing to git repo and master branch

**Comment by wjurkowlaniec** [comment]
I second @markkkkas  request, thank you in advance ;)

**Comment by markkkkas** [comment]
any updates?  @Turall

**Comment by sabuhish** [comment]
Sorry, we had a tough week though, I will go over PR in a few hours, @Turall will also review asap, thank you for your patience!

**Pull request merged**
